POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "1001",
  "password": "1001"
}

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "1007",
  "password": "1006"
}

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number": "1005",
  "password": "1005"
}

###